### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [multicolor-rgb/upload-plugin-for-bludit#2]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@alpernae) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by multicolor-rgb** [comment]
Ok done. Thanks for you help:) I love create for community Bludit and Getsimple cms, and great someone want help me make my plugin better.

**Comment by alpernae** [comment]
Hiii 

Can you pls sign up here and confirm my report?
https://huntr.dev
